export const projects = [
  {
    title: 'PurgeAI',
    desc: 'Purge AI is an AI-powered tool that analyzes GitHub PRs using LLMs and metadata extraction. It streamlines developer workflows with accurate labeling, concise summaries, and dynamic adaptation to different repositories, boosting speed, consistency, and review efficiency.',
    srcLink: 'https://github.com/satishydv/purge.ai',
    webLink: 'https://purgeai.abdullahtech.dev',
    skills: [
      'Typescript',
      'React',
      'NextJS',
      'Express',
      'Node JS',
      'OAuth2',
      'Prisma',
      'TailwindCSS',
      'Vercel',
    ],
    imgLink: '/projects/purgeailogo.webp',
    color: 'bg-blue-100 dark:bg-blue-950/30 border-blue-200 dark:border-blue-800',
  },
  {
    title: 'Privado',
    desc: 'Privado is a fast, secure private chat app powered by Socket.IO. Instantly connect, message friends, and enjoy real-time private conversations with no distractions. Simple, smooth, and built for people who value privacy and speed.',
    srcLink: 'https://github.com/satishydv/Web-Socket-Server-Sets',
    webLink: 'https://privado.abdullahtech.dev',
    skills: [
      'Typescript',
      'React',
      'NextJS',
      'Express',
      'Node JS',
      'Socket.IO',
      'TailwindCSS',
      'Golang',
      'Vercel',
    ],
    imgLink: '/projects/chat.png',
    color: 'bg-emerald-100 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-800',
  },
  {
    title: 'Github Metrics',
    desc: "Now you can Compare your Github Stats with the best in the world, be it Torvalds, Karpathy, Harkirat and who not. You think you're doing your best? have better PR's than someone? Lets see here mate.",
    srcLink: 'https://github.com/satishydv/Github-Metrics',
    webLink: 'https://githubstats.abdullahtech.dev',
    skills: ['Typescript', 'React', 'Express', 'TailwindCSS', 'Vite', 'Gemini', 'Zustand'],
    imgLink: '/projects/githublogo.png',
    color: 'bg-amber-100 dark:bg-amber-950/30 border-amber-200 dark:border-amber-800',
  },
  {
    title: 'React Flip Game',
    desc: 'Created a Fun to play Memory Game using React and TypeScript with dynamic grids support, dark and light themes and easy to hard levels with a very cool UI to interact with. Hope you enjoy it.',
    srcLink: 'https://github.com/satishydv/React-Flip-Game',
    webLink: 'https://flipgame.abdullahtech.dev/',
    skills: ['Typescript', 'React', 'TailwindCSS', 'next - themes', 'grids', 'Vercel', 'Zustand'],
    imgLink: '/projects/flipgame.webp',
    color: 'bg-indigo-100 dark:bg-indigo-950/30 border-indigo-200 dark:border-indigo-800',
  },
  {
    title: 'Go Http Server',
    desc: 'Made an Http Server in Go from scratch. A reliable Tcp connection using go std net library and unix system calls interacting with low level networking of the operating system.',
    srcLink: 'https://github.com/satishydv/http-Server-Go',
    webLink: 'https://github.com/satishydv/http-Server-Go',
    skills: ['Golang', 'Networking', 'HTTP', 'Operating System', 'TCP', 'Sys Calls', 'Unix'],
    imgLink: '/projects/gologo.webp',
    color: 'bg-sky-100 dark:bg-sky-950/30 border-sky-200 dark:border-sky-800',
  },
  {
    title: 'Cat Capture',
    desc: 'Capture your cats attention my simply playing the sounds you wanna talk with, its a simple fun side project i made only because i love my cat so much.',
    srcLink: 'https://github.com/satishydv/Meoww',
    webLink: 'https://meoww.abdullahtech.dev/',
    skills: [
      'Typescript',
      'Next js',
      'React',
      'Cat Images Api',
      'TailwindCSS',
      'Vercel',
      'Zustand',
    ],
    imgLink: '/projects/cat.webp',
    color: 'bg-rose-100 dark:bg-rose-950/30 border-rose-200 dark:border-rose-800',
  },
  {
    title: 'Draw',
    desc: 'Draw app that lets you sketch freely with smooth strokes, vibrant colors, and an intuitive interface, delivering a fast, minimal, and immersive digital drawing experience.',
    srcLink: 'https://github.com/satishydv/draw',
    webLink: 'https://draw.abdullahtech.dev/',
    skills: [
      'Typescript',
      'Next js',
      'React',
      'Cat Images Api',
      'TailwindCSS',
      'Vercel',
      'Zustand',
    ],
    imgLink: '/projects/cat.webp',
    color: 'bg-violet-100 dark:bg-violet-950/30 border-violet-200 dark:border-violet-800',
  },
];
