export const projects = [
  {
    title: 'Gitale',
    desc: "GitTale is a story-driven visualization tool for GitHub repositories. It transforms boring commit history into a readable, gamified narrative timeline with RPG-style elements, achievements, and unique collectibles and passport generation in differebt styles like cyberpunk, pixel art, etc.",
    srcLink: 'https://github.com/satishydv/GITTALE',
    webLink: 'https://gittale-omega.vercel.app/',
    skills: ['Typescript', 'React', 'Express', 'TailwindCSS', 'Vite', 'Gemini', 'Zustand'],
    imgLink: '/projects/githublogo.png',
    color: 'bg-amber-100 dark:bg-amber-950/30 border-amber-200 dark:border-amber-800',
  },
  {
    title: 'Resumind',
    desc: 'Resumind is an AI-powered tool that analyzes your resume using LLMs and metadata extraction. It streamlines developer workflows with accurate labeling, concise summaries, and dynamic adaptation to different repositories, boosting speed, consistency, and review efficiency.',
    srcLink: 'https://github.com/satishydv/ai-resume-analyzer',
    webLink: 'https://ai-resume-analyzer-lime-chi.vercel.app/',
    skills: [
      'Typescript',
      'React',
      'NextJS',
      'Express',
      'Node JS',
      'OAuth2',
      'Prisma',
      'TailwindCSS',
      'Vercel',
    ],
    imgLink: '/projects/purgeailogo.webp',
    color: 'bg-blue-100 dark:bg-blue-950/30 border-blue-200 dark:border-blue-800',
  },
  {
    title: 'Cloud Cost Optimizer',
    desc: 'Cloud cost optimization tool that helps businesses reduce their cloud infrastructure expenses by analyzing usage patterns and recommending cost-saving measures.',
    srcLink: 'https://github.com/satishydv/cloudcost-optimizer',
    webLink: 'https://cloudcost-optimizer.vercel.app/',
    skills: [
      'Typescript',
      'React',
      'NextJS',
      'Express',
      'Node JS',
      'Socket.IO',
      'TailwindCSS',
      'Golang',
      'Vercel',
    ],
    imgLink: '/projects/chat.png',
    color: 'bg-emerald-100 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-800',
  },

  {
    title: 'Zenplan Mobile App',
    desc: 'Zenplan is a mobile app that helps you manage your time and tasks. It is a simple and easy to use app that helps you stay organized and productive.',
    srcLink: 'https://github.com/satishydv/ZenPlan-Mobile-App',
    webLink: 'https://zen-plan-task-master.vercel.app/',
    skills: ['Typescript', 'React Native', 'next - themes', 'linear-gradient', 'Expo', 'Zustand'],
    imgLink: '/projects/flipgame.webp',
    color: 'bg-indigo-100 dark:bg-indigo-950/30 border-indigo-200 dark:border-indigo-800',
  },
  {
    title: 'ShopZone',
    desc: 'ShopZone is an e-commerce platform that allows users to browse and purchase products from various merchants. It provides a user-friendly interface for shopping, secure payment processing, and easy product management.',
    srcLink: 'https://github.com/satishydv/Ecommerce-2',
    webLink: 'https://ecommerce-2-rose.vercel.app/',
    skills: ['Typescript', 'React', 'NextJS', 'Express', 'Node JS', 'TailwindCSS', 'Vercel', 'Zustand'],
    imgLink: '/projects/gologo.webp',
    color: 'bg-sky-100 dark:bg-sky-950/30 border-sky-200 dark:border-sky-800',
  },
  {
    title: 'Cyber Cube',
    desc: 'Cyberpunk 3D Rubik\'s Cube game with multiple skins and 3D AI assistant its built using three js with matrix mathematics.',
    srcLink: 'https://github.com/satishydv/3d-cyber-cube',
    webLink: 'https://3d-cyber-cube.vercel.app/',
    skills: [
      'Typescript',
      'Next js',
      'React',
      'Three js',
      'GLSL Shaders',
      'Vercel',
      'Zustand',
    ],
    imgLink: '/projects/cat.webp',
    color: 'bg-rose-100 dark:bg-rose-950/30 border-rose-200 dark:border-rose-800',
  },
  {
    title: 'Lumina SaaS',
    desc: 'Landing page for Lumina SaaS, a software as a service platform offering innovative solutions for businesses.',
    srcLink: 'https://github.com/satishydv/Lumina-SaaS',
    webLink: 'https://lumina-saa-s.vercel.app/',
    skills: [
      'Typescript',
      'Next js',
      'React',
      'Framer Motion',
      'TailwindCSS',
      'Vercel',
      'Zustand',
    ],
    imgLink: '/projects/cat.webp',
    color: 'bg-violet-100 dark:bg-violet-950/30 border-violet-200 dark:border-violet-800',
  },
];
